### ISSUE TITLE
External DB server

### ISSUE THREAD

**Issue by johnwc** [nullconfig/phpipam#1]
Can you allow the app to be installed with using an external db server? Allowing to disable installing the mariadb pod.

**Comment by nullconfig** [comment]
@johnwc The main goal was to have it all self contained. I can see the benefit of running the chart and having it communicate with an external database. 

If you'd like you are more than welcome to submit a pull request and I'll put that in. Otherwise it'll probably be some time before I can get around to adding that updated behavior,as I have quite a bit of competing priorities at the moment. 

Thanks for submitting the suggestion!
